// Mapeo centralizado de íconos Font Awesome — ver CLAUDE.md: los componentes importan íconos desde
// aquí, no directamente de @fortawesome/free-solid-svg-icons.
import {
  faHospital,
  faGraduationCap,
  faRoad,
  faFaucetDrip,
  faHandHoldingHeart,
  faSeedling,
  faHouse,
  faMountain,
  faBolt,
  faPeopleGroup,
  faTractor,
  faCity,
  faShieldHalved,
  faLandmark,
  faUmbrellaBeach,
  faFileInvoice,
  faLayerGroup,
  faToggleOn,
  faToggleOff,
  faFileAlt,
  faPencil,
  faAngleLeft,
  faBars,
  faChevronRight,
  faChevronDown,
  faAnglesLeft,
  faAnglesRight,
  faCheck,
  faXmark,
  faTriangleExclamation,
  faUser,
  faLock,
  faEye,
  faEyeSlash,
  faRightToBracket,
  faCircleExclamation,
  faPlus,
  faGear,
  faHeadset,
  faCircleInfo,
  faRightFromBracket,
  faUserGear,
  faPen,
  faFileImport,
  faMagnifyingGlass,
  faStar,
  faFileCode,
  faRotate,
  faScrewdriverWrench,
  faBook,
  faArrowLeft,
  faChevronLeft,
  faCircleQuestion,
  faCircleCheck,
  faCircleXmark,
  faHourglassHalf,
  faEllipsisVertical,
  faTrash,
  faLightbulb,
  faWandMagicSparkles,
  faSpinner,
  faFont,
  faAlignLeft,
  faHashtag,
  faCalendarDays,
  faListCheck,
  faLink,
  faCircleDot,
  faTable,
  faSitemap,
  faImage,
  faSignature,
  faLocationDot,
  faArrowDown19,
  faSave,
  faLeaf,
  faGripVertical,
  faSearch,
  faCircle,
  faInfoCircle,
  faCopy,
  faFileExcel,
  faDownload,
  faFileExport,
  faTags,
  faArrowRotateLeft,
  faCircleUser,
  faCreditCard,
  faDesktop,
  faCartShopping,
  faUserPlus,
  faUserSlash,
  faUserCheck,
  faLockOpen,
  faMinus,
  faMobileScreenButton,
  faQrcode,
  faMoneyBillTransfer,
  faDisplay,
  faUsers,
  faFileLines,
  faClockRotateLeft,
  faFilter,
  faList,
  faBriefcase,
  faInbox,
  faUserGroup,
  faFileCirclePlus,
  faRobot,
  faPaperPlane,
  faChalkboardUser,
  faCalendarCheck,
  faUserTie,
  faDoorOpen,
  faCirclePlay,
  faComments,
  faVideo,
  faArrowRight,
  faBoxArchive,
  faCloudArrowUp,
  faFolderOpen,
  faArrowUpRightFromSquare,
  faBell,
  faCalendarWeek,
  faClock,
  faCalendarPlus,
  faCalendarXmark,
  faGlobe,
  faCrown,
  faEnvelope,
  type IconDefinition,
} from '@fortawesome/free-solid-svg-icons';
import type { RolUsuario, TipoInstrumento, TipologiaIoarr, TipoCampo, TipoColumna, SubtipoTabla, MetodoPago } from '@/types';

export const sectorIcons: Record<string, IconDefinition> = {
  faHospital,
  faGraduationCap,
  faRoad,
  faFaucetDrip,
  faHandHoldingHeart,
  faSeedling,
  faMountain,
  faBolt,
  faPeopleGroup,
  faTractor,
  faCity,
  faHouse,
  faShieldHalved,
  faLandmark,
  faUmbrellaBeach,
  faFileInvoice,
};

export const sectorIconList = [
  'faHospital',
  'faGraduationCap',
  'faMountain',
  'faFaucetDrip',
  'faHandHoldingHeart',
  'faSeedling',
  'faBolt',
  'faRoad',
  'faTractor',
  'faCity',
  'faHouse',
  'faPeopleGroup',
  'faShieldHalved',
  'faLandmark',
  'faUmbrellaBeach',
  'faFileInvoice',
] as const;

export const rolUsuarioLabels: Record<RolUsuario, string> = {
  superusuario: 'Superusuario',
  administrador: 'Administrador',
  cliente: 'Cliente',
  administrativo_asesorias: 'Administrativo de Asesorías',
  asesor: 'Asesor',
};

export const rolUsuarioIcons: Record<RolUsuario, IconDefinition> = {
  superusuario: faCrown,
  administrador: faUserGear,
  administrativo_asesorias: faUserGroup,
  cliente: faUser,
  asesor: faBriefcase,
};

export const metodoPagoIcons: Record<MetodoPago, IconDefinition> = {
  tarjeta: faCreditCard,
  yape: faMobileScreenButton,
  plin: faQrcode,
  mercado_pago: faCartShopping,
  '360pay': faMoneyBillTransfer,
};

export const metodoPagoLabels: Record<MetodoPago, string> = {
  tarjeta: 'Tarjeta (Stripe)',
  yape: 'Yape',
  plin: 'Plin',
  mercado_pago: 'Mercado Pago',
  '360pay': '360Pay',
};

export const instrumentoIcons: Record<TipoInstrumento, IconDefinition> = {
  formato: faFileInvoice,
  ioarr: faScrewdriverWrench,
  ficha_tecnica: faFileAlt,
  perfil: faBook,
};

export const instrumentoLabels: Record<TipoInstrumento, string> = {
  formato: 'Formato',
  ioarr: 'IOARR',
  ficha_tecnica: 'Ficha Técnica',
  perfil: 'Perfil',
};

export const tipologiaIoarrLabels: Record<TipologiaIoarr, string> = {
  optimizacion: 'Optimización',
  ampliacion_marginal: 'Ampliación marginal',
  reposicion: 'Reposición',
  rehabilitacion: 'Rehabilitación',
};

export const fieldTypeIcons: Record<TipoCampo, IconDefinition> = {
  texto_corto: faFont,
  texto_largo: faAlignLeft,
  numero: faHashtag,
  decimal: faFileInvoice,
  fecha: faCalendarDays,
  catalogo_simple: faListCheck,
  booleano: faListCheck,
  catalogo_encadenado: faLink,
  seleccion: faCircleDot,
  tabla: faTable,
  tabla_jerarquica: faSitemap,
  calculado: faLock,
  imagen: faImage,
  firma: faSignature,
  mapa_coordenadas: faLocationDot,
};

export const fieldTypeLabels: Record<TipoCampo, string> = {
  texto_corto: 'Texto corto',
  texto_largo: 'Texto largo',
  numero: 'Número',
  decimal: 'Decimal',
  fecha: 'Fecha',
  booleano: 'Booleano',
  catalogo_simple: 'Catálogo simple',
  catalogo_encadenado: 'Catálogo encadenado',
  seleccion: 'Selección',
  tabla: 'Tabla',
  tabla_jerarquica: 'Tabla jerárquica',
  calculado: 'Calculado',
  imagen: 'Imagen / croquis',
  firma: 'Firma',
  mapa_coordenadas: 'Coordenadas',
};

export const columnTypeLabels: Record<TipoColumna, string> = {
  texto_corto: 'Texto corto',
  texto_largo: 'Texto largo',
  numero: 'Número',
  decimal: 'Decimal',
  fecha: 'Fecha',
  booleano: 'Booleano',
  coordenadas: 'Coordenadas',
  calculado: 'Calculado',
  catalogo: 'Catálogo',
  catalogo_encadenado: 'Cat. encadenado',
  auto_numerico: 'Auto-numérico',
};

export const columnTypeIcons: Record<TipoColumna, IconDefinition> = {
  texto_corto: faFont,
  texto_largo: faAlignLeft,
  numero: faHashtag,
  decimal: faFileInvoice,
  fecha: faCalendarDays,
  booleano: faListCheck,
  coordenadas: faLocationDot,
  calculado: faLock,
  catalogo: faListCheck,
  catalogo_encadenado: faLink,
  auto_numerico: faArrowDown19,
};

export const subtipoTablaLabels: Record<SubtipoTabla, string> = {
  filas_dinamicas: 'Filas dinámicas',
  matriz_por_periodos: 'Columnas dinámicas',
  jerarquica: 'Jerárquica',
  jerarquica_dinamica: 'Jerárquica + columnas dinámicas',
};

// Únicamente estos se ofrecen en el selector de tipo de columna — catalogo/catalogo_encadenado/
// auto_numerico se mantienen en columnTypeIcons/Labels para columnas existentes, pero no son
// seleccionables aquí.
export const columnTypePrimitivos: TipoColumna[] = [
  'texto_corto',
  'texto_largo',
  'numero',
  'decimal',
  'fecha',
  'booleano',
  'coordenadas',
  'calculado',
];

export {
  faHouse,
  faLayerGroup,
  faToggleOn,
  faToggleOff,
  faPeopleGroup,
  faFileAlt,
  faPencil,
  faAngleLeft,
  faBars,
  faChevronRight,
  faChevronDown,
  faAnglesLeft,
  faAnglesRight,
  faCheck,
  faXmark,
  faTriangleExclamation,
  faUser,
  faLock,
  faEye,
  faEyeSlash,
  faRightToBracket,
  faCircleExclamation,
  faPlus,
  faGear,
  faHeadset,
  faCircleInfo,
  faRightFromBracket,
  faUserGear,
  faPen,
  faFileImport,
  faMagnifyingGlass,
  faStar,
  faFileCode,
  faRotate,
  faArrowLeft,
  faChevronLeft,
  faCircleQuestion,
  faCircleCheck,
  faCircleXmark,
  faHourglassHalf,
  faEllipsisVertical,
  faTrash,
  faLightbulb,
  faWandMagicSparkles,
  faSpinner,
  faSave,
  faLeaf,
  faGripVertical,
  faBolt,
  faSearch,
  faCircle,
  faInfoCircle,
  faAlignLeft,
  faTable,
  faImage,
  faCopy,
  faFileExcel,
  faDownload,
  faFileExport,
  faTags,
  faArrowRotateLeft,
  faShieldHalved,
  faCircleUser,
  faCreditCard,
  faDesktop,
  faCartShopping,
  faUserPlus,
  faUserSlash,
  faUserCheck,
  faLockOpen,
  faMinus,
  faDisplay,
  faUsers,
  faFileLines,
  faClockRotateLeft,
  faFilter,
  faList,
  faBriefcase,
  faInbox,
  faUserGroup,
  faFileCirclePlus,
  faRobot,
  faPaperPlane,
  faGraduationCap,
  faChalkboardUser,
  faCalendarCheck,
  faUserTie,
  faDoorOpen,
  faCirclePlay,
  faComments,
  faVideo,
  faCalendarDays,
  faFolderOpen,
  faArrowRight,
  faLocationDot,
  faBoxArchive,
  faCloudArrowUp,
  faArrowUpRightFromSquare,
  faBell,
  faCalendarWeek,
  faClock,
  faCalendarPlus,
  faCalendarXmark,
  faGlobe,
  faCrown,
  faEnvelope,
  faFileInvoice,
  faBook,
  faMoneyBillTransfer,
  faListCheck,
};
