// Solicitudes ficticias generadas en el FRONTEND para que "Mis consultas" (docente) se vea poblada
// en las pestañas "Por Agendar" y "Agendadas" durante una revisión de diseño — pedido explícito del
// usuario, no viene del backend ni se guarda en ningún lado (mismo criterio que ticketsDemoFake.ts).
// "Atendidas" ya tiene datos reales de sobra (Pedro Ríos, docente_id=6, tiene decenas de solicitudes
// 'completado') y no necesita nada ficticio. "Reprogramadas" queda vacía a propósito: ese tab todavía
// no filtra nada real (ver el comentario en MisConsultasPage.vue) — no hay campo/estado que fingir.
import type { SolicitudAsesoria } from '@/types';

const AHORA = Date.now();
const HORA_MS = 60 * 60 * 1000;

export function solicitudesFalsasPedroRios(docenteId: string): SolicitudAsesoria[] {
  return [
    // --- Por Agendar (pendiente / en_espera) ---
    {
      id: 'demo-fake-1',
      clienteId: 'demo-cliente-1',
      clienteNombre: 'Rosa Delgado Vigo',
      clienteFotoUrl: null,
      docenteId: null,
      docenteNombre: null,
      ejemploId: null,
      sectorId: 'demo-sector-1',
      sectorNombre: 'Salud',
      tipoDocumento: 'fichas_tecnicas',
      tipo: 'chat',
      estado: 'pendiente',
      mensajeInicial: 'No sé cómo calcular la brecha de servicio para mi proyecto.',
      horarioFecha: null,
      horarioHoraInicio: null,
      horarioHoraFin: null,
      linkReunion: null,
      slaVenceEn: new Date(AHORA + 18 * HORA_MS).toISOString(),
      calificacion: null,
      calificacionComentario: null,
      creadoEn: new Date(AHORA - 2 * HORA_MS).toISOString(),
      actualizadoEn: null,
    },
    {
      id: 'demo-fake-2',
      clienteId: 'demo-cliente-2',
      clienteNombre: 'Manuel Farfán Quispe',
      clienteFotoUrl: null,
      docenteId: null,
      docenteNombre: null,
      ejemploId: null,
      sectorId: 'demo-sector-2',
      sectorNombre: 'Educación',
      tipoDocumento: 'perfiles',
      tipo: 'video',
      estado: 'en_espera',
      mensajeInicial: 'Necesito revisar el análisis técnico antes de presentar mi perfil.',
      horarioFecha: null,
      horarioHoraInicio: null,
      horarioHoraFin: null,
      linkReunion: null,
      slaVenceEn: null,
      calificacion: null,
      calificacionComentario: null,
      creadoEn: new Date(AHORA - 26 * HORA_MS).toISOString(),
      actualizadoEn: null,
    },
    // --- Agendadas (asignado = chat ya aceptado / agendado = video con horario) ---
    {
      id: 'demo-fake-3',
      clienteId: 'demo-cliente-3',
      clienteNombre: 'Lucía Ramos Vega',
      clienteFotoUrl: null,
      docenteId,
      docenteNombre: 'Pedro Ríos',
      ejemploId: null,
      sectorId: 'demo-sector-3',
      sectorNombre: 'Agricultura y Riego',
      tipoDocumento: 'fichas_tecnicas',
      tipo: 'chat',
      estado: 'asignado',
      mensajeInicial: 'Tengo dudas sobre el horizonte de evaluación.',
      horarioFecha: null,
      horarioHoraInicio: null,
      horarioHoraFin: null,
      linkReunion: null,
      slaVenceEn: null,
      calificacion: null,
      calificacionComentario: null,
      creadoEn: new Date(AHORA - 5 * HORA_MS).toISOString(),
      actualizadoEn: new Date(AHORA - 4 * HORA_MS).toISOString(),
    },
    {
      id: 'demo-fake-4',
      clienteId: 'demo-cliente-4',
      clienteNombre: 'Jorge Salazar Nuñez',
      clienteFotoUrl: null,
      docenteId,
      docenteNombre: 'Pedro Ríos',
      ejemploId: null,
      sectorId: 'demo-sector-4',
      sectorNombre: 'Vivienda y Saneamiento',
      tipoDocumento: 'fichas_tecnicas',
      tipo: 'video',
      estado: 'agendado',
      mensajeInicial: 'Quisiera repasar la evaluación social de mi alternativa elegida.',
      horarioFecha: new Date(AHORA + 24 * HORA_MS).toISOString().slice(0, 10),
      horarioHoraInicio: '15:00',
      horarioHoraFin: '15:45',
      linkReunion: 'https://meet.demo/pf-abc123',
      slaVenceEn: null,
      calificacion: null,
      calificacionComentario: null,
      creadoEn: new Date(AHORA - 10 * HORA_MS).toISOString(),
      actualizadoEn: new Date(AHORA - 9 * HORA_MS).toISOString(),
    },
  ];
}
